# Generated by Django 4.1.6 on 2023-02-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maiinn', '0004_alter_userimage_usrr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userimage',
            name='id',
        ),
        migrations.AddField(
            model_name='userimage',
            name='sno',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
