# Generated by Django 4.1.6 on 2023-02-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maiinn', '0005_remove_userimage_id_userimage_sno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='images',
            field=models.ImageField(upload_to='mainn/images'),
        ),
    ]
