# Generated by Django 4.1.6 on 2023-03-07 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maiinn', '0006_alter_userimage_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userimage',
        ),
    ]
