# Generated by Django 4.1.6 on 2023-03-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maiinn', '0008_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='static/default.webp', upload_to='mainn/images'),
        ),
    ]
