# Generated by Django 4.1.6 on 2023-03-14 15:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maiinn', '0009_alter_profile_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='userProfile',
        ),
    ]
