# Generated by Django 4.1.6 on 2023-03-15 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maiinn', '0010_rename_profile_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='static/default.webp', upload_to='media/mainn/images'),
        ),
    ]
