# Generated by Django 4.1.6 on 2023-03-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maiinn', '0014_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='mainn/images/default.webp', upload_to='mainn/images/'),
        ),
    ]
