# Generated by Django 4.1.5 on 2023-02-03 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slugg',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
