# Generated by Django 4.1.5 on 2023-02-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_slugg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slugg',
            field=models.CharField(max_length=100),
        ),
    ]
