# Generated by Django 4.1.5 on 2023-02-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpost_slugg'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='aboutauthor',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
